### ISSUE TITLE
On slow windows 10 - Error: Timed out waiting for: http://localhost:6001

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/web-app-fundamentals#8]
When testing `web-app-fundamentals` on slow Windows 10 ([virtualbox](https://www.virtualbox.org/) windows 10)

I am getting this error:

<details>
  <summary markdown="span">Timed out waiting for: http://localhost:6001</summary>

```
🐨  Let's get learning!
Local:            http://localhost:5639
On Your Network:  http://10.0.2.15:5639
Press Ctrl+C to stop
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001] > dev
[01.styling.01.problem.public-links:6001] > cross-env NODE_ENV=development run-p dev:*
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001] > dev:server
[01.styling.01.problem.public-links:6001] > cross-env MOCKS=true tsx watch --clear-screen=false --ignore "app/**" --ignore "build/**" --ignore "node_modules/**" ./index.js
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001] > dev:remix
[01.styling.01.problem.public-links:6001] > cross-env PORT="" remix dev
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001] 🔶 Mock server installed
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001] Express server listening on port 6001
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001] HEAD / 500 1509 - 5.980 ms
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001] Error: Cannot find module 'C:\projects\web-app-fundamentals\exercises\01.styling\01.problem.public-links\build'
[01.styling.01.problem.public-links:6001] Require stack:
[01.styling.01.problem.public-links:6001] - C:\projects\web-app-fundamentals\exercises\01.styling\01.problem.public-links\server\index.ts
[01.styling.01.problem.public-links:6001] - C:\projects\web-app-fundamentals\exercises\01.styling\01.problem.public-links\index.js
[01.styling.01.problem.public-links:6001]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
[01.styling.01.problem.public-links:6001]     at Function.u.default._resolveFilename (C:\projects\web-app-fundamentals\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:1519)
[01.styling.01.problem.public-links:6001]     at Function.Module._load (node:internal/modules/cjs/loader:934:27)
[01.styling.01.problem.public-links:6001]     at Module.require (node:internal/modules/cjs/loader:1157:19)
[01.styling.01.problem.public-links:6001]     at require (node:internal/modules/helpers:119:18)
[01.styling.01.problem.public-links:6001]     at C:\projects\web-app-fundamentals\exercises\01.styling\01.problem.public-links\server\index.ts:2:1628
[01.styling.01.problem.public-links:6001]     at Layer.handle [as handle_request] (C:\projects\web-app-fundamentals\node_modules\express\lib\router\layer.js:8:864)
[01.styling.01.problem.public-links:6001]     at next (C:\projects\web-app-fundamentals\node_modules\express\lib\router\route.js:8:1411)
[01.styling.01.problem.public-links:6001]     at next (C:\projects\web-app-fundamentals\node_modules\express\lib\router\route.js:8:1340)
[01.styling.01.problem.public-links:6001]     at next (C:\projects\web-app-fundamentals\node_modules\express\lib\router\route.js:8:1340)
[01.styling.01.problem.public-links:6001]
....
many times the same error

[01.styling.01.problem.public-links:6001]
Error: Timed out waiting for: http://localhost:6001
    at C:\projects\web-app-fundamentals\node_modules\wait-on\lib\wait-on.js:132:31
    at doInnerSub (C:\projects\web-app-fundamentals\node_modules\rxjs\src\internal\operators\mergeInternals.ts:71:15)
    at outerNext (C:\projects\web-app-fundamentals\node_modules\rxjs\src\internal\operators\mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (C:\projects\web-app-fundamentals\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (C:\projects\web-app-fundamentals\node_modules\rxjs\src\internal\Subscriber.ts:75:12)
    at AsyncAction.<anonymous> (C:\projects\web-app-fundamentals\node_modules\rxjs\src\internal\observable\timer.ts:173:20)
    at AsyncAction._execute (C:\projects\web-app-fundamentals\node_modules\rxjs\src\internal\scheduler\AsyncAction.ts:120:12)
    at AsyncAction.execute (C:\projects\web-app-fundamentals\node_modules\rxjs\src\internal\scheduler\AsyncAction.ts:95:24)
    at AsyncScheduler.flush (C:\projects\web-app-fundamentals\node_modules\rxjs\src\internal\scheduler\AsyncScheduler.ts:40:27)
    at listOnTimeout (node:internal/timers:573:17)
[01.styling.01.problem.public-links:6001] HEAD / 200 - - 1987.053 ms
[01.styling.01.problem.public-links:6001]
[01.styling.01.problem.public-links:6001] HEAD / 200 - - 30.604 ms
[01.styling.01.problem.public-links:6001]
Terminate batch job (Y/N)? closing exercises.01.styling.01.problem.public-links
```
</details>

Look like that increasing the timeout in `process-manager.server.ts` works
```diff
export async function waitOnApp(app: App) {
	if (app.dev.type === 'script') {
		return waitOn({
			resources: [`http://localhost:${app.dev.portNumber}`],
-			timeout: 15_000,
+			timeout: 10_000,
		})
	}
}
```

However the styles don't load most of the time without hitting F5.
[maybe 200ms timeout is to short ](https://github.com/epicweb-dev/kcdshop/commit/fbd3fadd7cc8caee119ee9de84dcfc7a15f34df9)

maybe this issue need to be in kcdshop

**Comment by kentcdodds** [comment]
Those errors make it look like the KCDShop server wasn't running. Are you sure it was?

I think if it takes that long to startup the server we should display an error and present them with a button that will check manually.

**Comment by onemen** [comment]
> Those errors make it look like the KCDShop server wasn't running. Are you sure it was?

If I will see these errors again I will check it.

> I think if it takes that long to startup the server we should display an error and present them with a button that will check manually.

Maybe it is happened only on first run of the app, i there any build process that take time?

**Comment by kentcdodds** [comment]
Please bring this up again if you see it. Thanks!
